<a href="https://colab.research.google.com/github/jaikla-tuwanon/ai-650710159/blob/main/dp_and_fe_for_student_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [70]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import warnings
warnings.filterwarnings('ignore')

In [71]:
df=pd.read_csv('student.csv')

In [72]:
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-05
2,64003,NaN,NaN,Male,Science,3.67,175.0,NaN,25.0,2024-01-13
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30
4,64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-27
5,64006,กานต์,150.0,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-23
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-05
7,64008,จิรา,20.0,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23
8,64009,ชนาธิป,23.0,M,Arts,3.34,163.0,55.0,22.0,2024-02-11
9,64010,ดารา,21.0,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-03
10,64011,ธีระ,NaN,NaN,NaN,3.78,NaN,68.0,NaN,2024-01-07
11,64012,นภา,22.0,ชาย,วิทย์,NaN,171.0,NaN,16.0,2023-12-26
12,64013,บุญมี,20.0,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2023-12-26
13,64014,ปรีชา,21.0,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-08
14,64015,พิมพ์,22.0,Female,Sci,3.67,162.0,56.0,26.0,2024-02-06
15,64016,ภูมิ,19.0,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20
16,64017,มานี,20.0,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-24
17,64018,ยุพา,21.0,หญิง,NaN,3.23,161.0,50.0,27.0,2024-01-08
18,64019,รัตนา,NaN,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2023-12-18
19,64020,ลัดดา,22.0,NaN,Science,3.45,168.0,64.0,23.0,2024-01-06

#การจัดการข้อมูลหาย

-ลบแถวที่มีค่าหาย

In [73]:
df_clean = df.dropna()

In [74]:
print(f"จำนวนแถวก่อนลบค่าที่หายไป: {len(df)} แถว, จำนวนแถวหลังลบ: {len(df_clean)} แถว")

จำนวนแถวก่อนลบค่าที่หายไป: 20 แถว, จำนวนแถวหลังลบ: 14 แถว

In [75]:
df_clean

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-05
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30
4,64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-27
5,64006,กานต์,150.0,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-23
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-05
7,64008,จิรา,20.0,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23
8,64009,ชนาธิป,23.0,M,Arts,3.34,163.0,55.0,22.0,2024-02-11
9,64010,ดารา,21.0,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-03
12,64013,บุญมี,20.0,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2023-12-26
13,64014,ปรีชา,21.0,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-08
14,64015,พิมพ์,22.0,Female,Sci,3.67,162.0,56.0,26.0,2024-02-06
15,64016,ภูมิ,19.0,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20
16,64017,มานี,20.0,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-24

-เติมค่าด้วยค่าเฉลี่ย "(ใช้กับตัวเลข)"

In [76]:
mean_age = df['อายุ'].mean()
df['อายุ'].fillna(mean_age, inplace=True)

In [77]:
# เติมค่าว่างในคอลัมน์ 'GPA' ด้วยค่าเฉลี่ย
df['GPA'] = df['GPA'].fillna(df['GPA'].mean())

In [78]:
# เติมค่าว่างในคอลัมน์ 'ส่วนสูง_cm' ด้วยค่าเฉลี่ย
df['ส่วนสูง_cm'] = df['ส่วนสูง_cm'].fillna(df['ส่วนสูง_cm'].mean())

In [79]:
# เติมค่าว่างในคอลัมน์ 'น้ำหนัก_kg' ด้วยค่าเฉลี่ย
df['น้ำหนัก_kg'] = df['น้ำหนัก_kg'].fillna(df['น้ำหนัก_kg'].mean())

In [80]:
# เติมค่าว่างในคอลัมน์ 'ชั่วโมงเรียน_ต่อสัปดาห์' ด้วยค่าเฉลี่ย
df['ชั่วโมงเรียน_ต่อสัปดาห์'] = df['ชั่วโมงเรียน_ต่อสัปดาห์'].fillna(df['ชั่วโมงเรียน_ต่อสัปดาห์'].mean())

In [81]:
print(f"ค่าเฉลี่ยอายุ: {mean_age:.2f} ปี")
print(f"ค่าเฉลี่ย GPA: {mean_GPA:.2f} ")
print(f"ค่าเฉลี่ยส่วนสูง: {mean_heigth:.2f} cm")
print(f"ค่าเฉลี่ยน้ำหนัก: {mean_weigth:.2f} kg")
print(f"ค่าเฉลี่ยชั่วโมงเรียนต่อสัปดาห์: {mean_hourBerweek:.2f} ชั่วโมง/สัปดาห์")

ค่าเฉลี่ยอายุ: 28.47 ปี
ค่าเฉลี่ย GPA: 3.25
ค่าเฉลี่ยส่วนสูง: 167.68 cm
ค่าเฉลี่ยน้ำหนัก: 63.61 kg
ค่าเฉลี่ยชั่วโมงเรียนต่อสัปดาห์: 21.39 ชั่วโมง/สัปดาห์

In [82]:
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.000000,ชาย,วิทยาศาสตร์,3.210000,170.000000,65.000000,15.000000,2024-01-23
1,64002,สมหญิง,21.000000,หญิง,วิทย์,3.450000,165.000000,58.000000,20.000000,2024-02-05
2,64003,NaN,28.470588,Male,Science,3.670000,175.000000,63.611111,25.000000,2024-01-13
3,64004,สมศักดิ์,22.000000,ช,คณะวิทยาศาสตร์,-1.000000,168.000000,70.000000,10.000000,2023-12-30
4,64005,สมใจ,19.000000,ญ,วิศวะ,3.890000,160.000000,52.000000,30.000000,2024-01-27
5,64006,กานต์,150.000000,ชาย,Engineering,3.120000,172.000000,75.000000,12.000000,2023-12-23
6,64007,กิตติ,21.000000,หญิง,วิศวกรรม,4.500000,158.000000,48.000000,35.000000,2024-01-05
7,64008,จิรา,20.000000,F,ศิลปศาสตร์,2.980000,180.000000,82.000000,18.000000,2024-01-23
8,64009,ชนาธิป,23.000000,M,Arts,3.340000,163.000000,55.000000,22.000000,2024-02-11
9,64010,ดารา,21.000000,หญิง,ศิลป์,3.560000,167.000000,60.000000,28.000000,2024-01-03
10,64011,ธีระ,28.470588,NaN,NaN,3.780000,167.684211,68.000000,21.388889,2024-01-07
11,64012,นภา,22.000000,ชาย,วิทย์,3.246111,171.000000,63.611111,16.000000,2023-12-26
12,64013,บุญมี,20.000000,หญิง,วิศวฯ,3.230000,169.000000,72.000000,24.000000,2023-12-26
13,64014,ปรีชา,21.000000,ชาย,Liberal Arts,3.450000,164.000000,54.000000,19.000000,2024-01-08
14,64015,พิมพ์,22.000000,Female,Sci,3.670000,162.000000,56.000000,26.000000,2024-02-06
15,64016,ภูมิ,19.000000,ช,วิทยาศาสตร์,3.890000,173.000000,78.000000,14.000000,2024-01-20
16,64017,มานี,20.000000,ญ,วิศวกรรมศาสตร์,3.010000,166.000000,62.000000,21.000000,2024-01-24
17,64018,ยุพา,21.000000,หญิง,NaN,3.230000,161.000000,50.000000,27.000000,2024-01-08
18,64019,รัตนา,28.470588,ชาย,ศิลปศาสตร์,3.246111,174.000000,76.000000,21.388889,2023-12-18
19,64020,ลัดดา,22.000000,NaN,Science,3.450000,168.000000,64.000000,23.000000,2024-01-06

-เติมค่าด้วยค่าที่พบบ่อยที่สุด "(ใช้กับตัวอักษร)"

1.1 ทำให้ข้อมูลเป็นมาตรฐาน

In [83]:
def standardize_faculty(เพศ):
    if เพศ in ['M', 'ชาย', 'Male', 'ช']:
        return 'M'
    elif เพศ in ['F', 'หญิง', 'Female','ญ']:
        return 'F'
    else:
        return เพศ

# ใช้งาน
df['เพศ_มาตรฐาน'] = df['เพศ'].apply(standardize_faculty)

In [84]:
def standardize_faculty(คณะ):
    if คณะ in ['วิทย์', 'วิทยาศาสตร์', 'Science','คณะวิทยาศาสตร์','Sci']:
        return 'วิทย์'
    elif คณะ in ['ศิลป์', 'Arts', 'ศิลปศาสตร์','Liberal Arts']:
        return 'ศิลป์'
    elif คณะ in ['วิศวะ', 'Engineering', 'วิศวกรรม','วิศวฯ','วิศวกรรมศาสตร์']:
        return 'วิศวะ'
    else:
        return คณะ

# ใช้งาน
df['คณะ_มาตรฐาน'] = df['คณะ'].apply(standardize_faculty)

In [85]:
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน,เพศ_มาตรฐาน,คณะ_มาตรฐาน
0,64001,สมชาย,20.000000,ชาย,วิทยาศาสตร์,3.210000,170.000000,65.000000,15.000000,2024-01-23,M,วิทย์
1,64002,สมหญิง,21.000000,หญิง,วิทย์,3.450000,165.000000,58.000000,20.000000,2024-02-05,F,วิทย์
2,64003,NaN,28.470588,Male,Science,3.670000,175.000000,63.611111,25.000000,2024-01-13,M,วิทย์
3,64004,สมศักดิ์,22.000000,ช,คณะวิทยาศาสตร์,-1.000000,168.000000,70.000000,10.000000,2023-12-30,M,วิทย์
4,64005,สมใจ,19.000000,ญ,วิศวะ,3.890000,160.000000,52.000000,30.000000,2024-01-27,F,วิศวะ
5,64006,กานต์,150.000000,ชาย,Engineering,3.120000,172.000000,75.000000,12.000000,2023-12-23,M,วิศวะ
6,64007,กิตติ,21.000000,หญิง,วิศวกรรม,4.500000,158.000000,48.000000,35.000000,2024-01-05,F,วิศวะ
7,64008,จิรา,20.000000,F,ศิลปศาสตร์,2.980000,180.000000,82.000000,18.000000,2024-01-23,F,ศิลป์
8,64009,ชนาธิป,23.000000,M,Arts,3.340000,163.000000,55.000000,22.000000,2024-02-11,M,ศิลป์
9,64010,ดารา,21.000000,หญิง,ศิลป์,3.560000,167.000000,60.000000,28.000000,2024-01-03,F,ศิลป์
10,64011,ธีระ,28.470588,NaN,NaN,3.780000,167.684211,68.000000,21.388889,2024-01-07,NaN,NaN
11,64012,นภา,22.000000,ชาย,วิทย์,3.246111,171.000000,63.611111,16.000000,2023-12-26,M,วิทย์
12,64013,บุญมี,20.000000,หญิง,วิศวฯ,3.230000,169.000000,72.000000,24.000000,2023-12-26,F,วิศวะ
13,64014,ปรีชา,21.000000,ชาย,Liberal Arts,3.450000,164.000000,54.000000,19.000000,2024-01-08,M,ศิลป์
14,64015,พิมพ์,22.000000,Female,Sci,3.670000,162.000000,56.000000,26.000000,2024-02-06,F,วิทย์
15,64016,ภูมิ,19.000000,ช,วิทยาศาสตร์,3.890000,173.000000,78.000000,14.000000,2024-01-20,M,วิทย์
16,64017,มานี,20.000000,ญ,วิศวกรรมศาสตร์,3.010000,166.000000,62.000000,21.000000,2024-01-24,F,วิศวะ
17,64018,ยุพา,21.000000,หญิง,NaN,3.230000,161.000000,50.000000,27.000000,2024-01-08,F,NaN
18,64019,รัตนา,28.470588,ชาย,ศิลปศาสตร์,3.246111,174.000000,76.000000,21.388889,2023-12-18,M,ศิลป์
19,64020,ลัดดา,22.000000,NaN,Science,3.450000,168.000000,64.000000,23.000000,2024-01-06,NaN,วิทย์

1.2 เติมค่าด้วยค่าที่พบบ่อยที่สุด

In [86]:
# เติมค่าว่างในคอลัมน์ 'เพศ_มาตรฐาน' ด้วยค่าที่พบบ่อยที่สุด
df['เพศ_มาตรฐาน'] = df['เพศ_มาตรฐาน'].fillna(df['เพศ_มาตรฐาน'].mode()[0])

In [87]:
# เติมค่าว่างในคอลัมน์ 'คณะ_มาตรฐาน' ด้วยค่าที่พบบ่อยที่สุด
df['คณะ_มาตรฐาน'] = df['คณะ_มาตรฐาน'].fillna(df['คณะ_มาตรฐาน'].mode()[0])

In [88]:
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน,เพศ_มาตรฐาน,คณะ_มาตรฐาน
0,64001,สมชาย,20.000000,ชาย,วิทยาศาสตร์,3.210000,170.000000,65.000000,15.000000,2024-01-23,M,วิทย์
1,64002,สมหญิง,21.000000,หญิง,วิทย์,3.450000,165.000000,58.000000,20.000000,2024-02-05,F,วิทย์
2,64003,NaN,28.470588,Male,Science,3.670000,175.000000,63.611111,25.000000,2024-01-13,M,วิทย์
3,64004,สมศักดิ์,22.000000,ช,คณะวิทยาศาสตร์,-1.000000,168.000000,70.000000,10.000000,2023-12-30,M,วิทย์
4,64005,สมใจ,19.000000,ญ,วิศวะ,3.890000,160.000000,52.000000,30.000000,2024-01-27,F,วิศวะ
5,64006,กานต์,150.000000,ชาย,Engineering,3.120000,172.000000,75.000000,12.000000,2023-12-23,M,วิศวะ
6,64007,กิตติ,21.000000,หญิง,วิศวกรรม,4.500000,158.000000,48.000000,35.000000,2024-01-05,F,วิศวะ
7,64008,จิรา,20.000000,F,ศิลปศาสตร์,2.980000,180.000000,82.000000,18.000000,2024-01-23,F,ศิลป์
8,64009,ชนาธิป,23.000000,M,Arts,3.340000,163.000000,55.000000,22.000000,2024-02-11,M,ศิลป์
9,64010,ดารา,21.000000,หญิง,ศิลป์,3.560000,167.000000,60.000000,28.000000,2024-01-03,F,ศิลป์
10,64011,ธีระ,28.470588,NaN,NaN,3.780000,167.684211,68.000000,21.388889,2024-01-07,F,วิทย์
11,64012,นภา,22.000000,ชาย,วิทย์,3.246111,171.000000,63.611111,16.000000,2023-12-26,M,วิทย์
12,64013,บุญมี,20.000000,หญิง,วิศวฯ,3.230000,169.000000,72.000000,24.000000,2023-12-26,F,วิศวะ
13,64014,ปรีชา,21.000000,ชาย,Liberal Arts,3.450000,164.000000,54.000000,19.000000,2024-01-08,M,ศิลป์
14,64015,พิมพ์,22.000000,Female,Sci,3.670000,162.000000,56.000000,26.000000,2024-02-06,F,วิทย์
15,64016,ภูมิ,19.000000,ช,วิทยาศาสตร์,3.890000,173.000000,78.000000,14.000000,2024-01-20,M,วิทย์
16,64017,มานี,20.000000,ญ,วิศวกรรมศาสตร์,3.010000,166.000000,62.000000,21.000000,2024-01-24,F,วิศวะ
17,64018,ยุพา,21.000000,หญิง,NaN,3.230000,161.000000,50.000000,27.000000,2024-01-08,F,วิทย์
18,64019,รัตนา,28.470588,ชาย,ศิลปศาสตร์,3.246111,174.000000,76.000000,21.388889,2023-12-18,M,ศิลป์
19,64020,ลัดดา,22.000000,NaN,Science,3.450000,168.000000,64.000000,23.000000,2024-01-06,F,วิทย์

-การจัดการค่าผิดปกติ

In [89]:
print(f"\nค่าเฉลี่ยอายุ (รวมค่าผิดปกติ) - {df['อายุ'].mean():.2f}")

# ใช้ IQR (Interquartile Range)
Q1 = df['อายุ'].quantile(0.25)
Q3 = df['อายุ'].quantile(0.75)
IQR = Q3 - Q1

# กำหนดขอบเขต
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# กรองค่าผิดปกติ
df_no_outliers = df[(df['อายุ'] >= lower_bound) & (df['อายุ'] <= upper_bound)]

ค่าเฉลี่ยอายุ (รวมค่าผิดปกติ) - 28.47

In [90]:
print(f"\nขอบเขตล่าง - {lower_bound}")
print(f"ขอบเขตบน - {upper_bound}")

ขอบเขตล่าง - 16.625
ขอบเขตบน - 25.625

In [91]:
print("\nข้อมูลหลังจากการกรองค่าผิดปกติ:")

ข้อมูลหลังจากการกรองค่าผิดปกติ:

In [92]:
df_no_outliers

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน,เพศ_มาตรฐาน,คณะ_มาตรฐาน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.210000,170.0,65.000000,15.0,2024-01-23,M,วิทย์
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.450000,165.0,58.000000,20.0,2024-02-05,F,วิทย์
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.000000,168.0,70.000000,10.0,2023-12-30,M,วิทย์
4,64005,สมใจ,19.0,ญ,วิศวะ,3.890000,160.0,52.000000,30.0,2024-01-27,F,วิศวะ
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.500000,158.0,48.000000,35.0,2024-01-05,F,วิศวะ
7,64008,จิรา,20.0,F,ศิลปศาสตร์,2.980000,180.0,82.000000,18.0,2024-01-23,F,ศิลป์
8,64009,ชนาธิป,23.0,M,Arts,3.340000,163.0,55.000000,22.0,2024-02-11,M,ศิลป์
9,64010,ดารา,21.0,หญิง,ศิลป์,3.560000,167.0,60.000000,28.0,2024-01-03,F,ศิลป์
11,64012,นภา,22.0,ชาย,วิทย์,3.246111,171.0,63.611111,16.0,2023-12-26,M,วิทย์
12,64013,บุญมี,20.0,หญิง,วิศวฯ,3.230000,169.0,72.000000,24.0,2023-12-26,F,วิศวะ
13,64014,ปรีชา,21.0,ชาย,Liberal Arts,3.450000,164.0,54.000000,19.0,2024-01-08,M,ศิลป์
14,64015,พิมพ์,22.0,Female,Sci,3.670000,162.0,56.000000,26.0,2024-02-06,F,วิทย์
15,64016,ภูมิ,19.0,ช,วิทยาศาสตร์,3.890000,173.0,78.000000,14.0,2024-01-20,M,วิทย์
16,64017,มานี,20.0,ญ,วิศวกรรมศาสตร์,3.010000,166.0,62.000000,21.0,2024-01-24,F,วิศวะ
17,64018,ยุพา,21.0,หญิง,NaN,3.230000,161.0,50.000000,27.0,2024-01-08,F,วิทย์
19,64020,ลัดดา,22.0,NaN,Science,3.450000,168.0,64.000000,23.0,2024-01-06,F,วิทย์

In [93]:
print(f"ค่าเฉลี่ยอายุ (หลังกรองค่าผิดปกติ): {df_no_outliers['อายุ'].mean():.2f} ปี")

ค่าเฉลี่ยอายุ (หลังกรองค่าผิดปกติ): 20.88 ปี

# การสร้างคุณลักษณะใหม่

แปลงข้อมูลประเภทเป็นตัวเลข

In [94]:
# สร้าง DataFrame สำหรับ One-Hot Encoding
data = df[['ชื่อ', 'คณะ_มาตรฐาน']].copy()

In [95]:
# ทำ One-Hot Encoding บนคอลัมน์ 'คณะ_มาตรฐาน'
data_encoded = pd.get_dummies(data, columns=['คณะ_มาตรฐาน'])

In [96]:
data_encoded*1

        ชื่อ  คณะ_มาตรฐาน_วิทย์  คณะ_มาตรฐาน_วิศวะ  คณะ_มาตรฐาน_ศิลป์
0      สมชาย                  1                  0                  0
1     สมหญิง                  1                  0                  0
2        NaN                  1                  0                  0
3   สมศักดิ์                  1                  0                  0
4       สมใจ                  0                  1                  0
5      กานต์                  0                  1                  0
6      กิตติ                  0                  1                  0
7       จิรา                  0                  0                  1
8     ชนาธิป                  0                  0                  1
9       ดารา                  0                  0                  1
10      ธีระ                  1                  0                  0
11       นภา                  1                  0                  0
12     บุญมี                  0                  1                  0
13     ปรีชา                  0                  0                  1
14     พิมพ์                  1                  0                  0
15      ภูมิ                  1                  0                  0
16      มานี                  0                  1                  0
17      ยุพา                  1                  0                  0
18     รัตนา                  0                  0                  1
19     ลัดดา                  1                  0                  0

การสร้าง Feature จากวันเวลา

In [97]:
# สร้าง DataFrame สำหรับ Feature จากวันที่
data_register = df[['ชื่อ', 'วันที่ลงทะเบียน']].copy()
data_register['วัน'] = pd.to_datetime(data_register['วันที่ลงทะเบียน'])

In [98]:
data_register['วันในสัปดาห์'] = data_register['วัน'].dt.day_name()

In [99]:
data_register['วันในสัปดาห์']

0       Tuesday
1        Monday
2      Saturday
3      Saturday
4      Saturday
5      Saturday
6        Friday
7       Tuesday
8        Sunday
9     Wednesday
10       Sunday
11      Tuesday
12      Tuesday
13       Monday
14      Tuesday
15     Saturday
16    Wednesday
17       Monday
18       Monday
19     Saturday
Name: วันในสัปดาห์, dtype: object

In [100]:
data_register

        ชื่อ วันที่ลงทะเบียน        วัน วันในสัปดาห์
0      สมชาย      2024-01-23 2024-01-23      Tuesday
1     สมหญิง      2024-02-05 2024-02-05       Monday
2        NaN      2024-01-13 2024-01-13     Saturday
3   สมศักดิ์      2023-12-30 2023-12-30     Saturday
4       สมใจ      2024-01-27 2024-01-27     Saturday
5      กานต์      2023-12-23 2023-12-23     Saturday
6      กิตติ      2024-01-05 2024-01-05       Friday
7       จิรา      2024-01-23 2024-01-23      Tuesday
8     ชนาธิป      2024-02-11 2024-02-11       Sunday
9       ดารา      2024-01-03 2024-01-03    Wednesday
10      ธีระ      2024-01-07 2024-01-07       Sunday
11       นภา      2023-12-26 2023-12-26      Tuesday
12     บุญมี      2023-12-26 2023-12-26      Tuesday
13     ปรีชา      2024-01-08 2024-01-08       Monday
14     พิมพ์      2024-02-06 2024-02-06      Tuesday
15      ภูมิ      2024-01-20 2024-01-20     Saturday
16      มานี      2024-01-24 2024-01-24    Wednesday
17      ยุพา      2024-01-08 2024-01-08       Monday
18     รัตนา      2023-12-18 2023-12-18       Monday
19     ลัดดา      2024-01-06 2024-01-06     Saturday

การรวม Features

In [101]:
# สร้าง DataFrame สำหรับ Feature ด้านสุขภาพ
student_health = df[['ชื่อ', 'ส่วนสูง_cm', 'น้ำหนัก_kg']].copy()

# สร้าง BMI
student_health['BMI'] = student_health['น้ำหนัก_kg'] / (student_health['ส่วนสูง_cm']/100)**2
student_health['สุขภาพ'] = pd.cut(student_health['BMI'],
                                   bins=[0, 18.5, 25, 30, 100],
                                   labels=['ผอม', 'ปกติ', 'อ้วน', 'อ้วนมาก'])

In [102]:
student_health[['ชื่อ', 'BMI', 'สุขภาพ']]

        ชื่อ        BMI สุขภาพ
0      สมชาย  22.491349   ปกติ
1     สมหญิง  21.303949   ปกติ
2        NaN  20.770975   ปกติ
3   สมศักดิ์  24.801587   ปกติ
4       สมใจ  20.312500   ปกติ
5      กานต์  25.351541   อ้วน
6      กิตติ  19.227688   ปกติ
7       จิรา  25.308642   อ้วน
8     ชนาธิป  20.700817   ปกติ
9       ดารา  21.513859   ปกติ
10      ธีระ  24.183802   ปกติ
11       นภา  21.754082   ปกติ
12     บุญมี  25.209201   อ้วน
13     ปรีชา  20.077335   ปกติ
14     พิมพ์  21.338211   ปกติ
15      ภูมิ  26.061679   อ้วน
16      มานี  22.499637   ปกติ
17      ยุพา  19.289379   ปกติ
18     รัตนา  25.102391   อ้วน
19     ลัดดา  22.675737   ปกติ